#!/usr/bin/with-contenv bash

set -euo pipefail

# create folders
mkdir -p "${KARADAV_PATH}"

# install app
if [ ! -e "${KARADAV_PATH}/www/index.php" ]; then
    unzip /app/karadav.zip -d /tmp
    mv /tmp/karadav-main/* "$KARADAV_PATH"
    chown abc:abc -R \
        "${KARADAV_PATH}"
fi
