#!/usr/bin/with-contenv bash

# copy config
if [[ ! -f "${KARADAV_PATH}/config.local.php" ]]; then
    cp /defaults/config.php "${KARADAV_PATH}/config.local.php"
    echo "" >> "${KARADAV_PATH}/config.local.php"
    echo "const WWW_URL = '${KARADAV_WEB_URL}';" >> "${KARADAV_PATH}/config.local.php"

    if [[ -n "${KARADAV_SECRET_KEY}" ]]; then
        echo "const SECRET_KEY = '${KARADAV_SECRET_KEY}';" >> "${KARADAV_PATH}/config.local.php"
    elif [[ -n "${KARADAV_SECRET_KEY_FILE}" ]]; then
        echo "const SECRET_KEY = '$(cat $KARADAV_SECRET_KEY_FILE)';" >> "${KARADAV_PATH}/config.local.php"
    fi
fi

# permissions
chown abc:abc \
    "${KARADAV_PATH}/config.local.php"
